### ISSUE TITLE
Unclear no_mailbox, short_mailbox, full_mailbox labels 

### ISSUE THREAD

**Issue by websafe** [kitist/html5_notifier#14]
Hello @kitist,

I'm translating `html5_notifier` and the `no_mailbox`, `short_mailbox`, `full_mailbox` labels seem to be kinda unclear. I'm checking the German translation now and I guess these are folders, not mailboxes?

**Comment by kitist** [comment]
Hi @websafe. you are right. It means folders.

**Comment by websafe** [comment]
OK :-)
