### ISSUE TITLE
no html5 notifications

### ISSUE THREAD

**Issue by denik84** [kitist/html5_notifier#5]
As you can see in my screenshot, the test of the html5_notifier works well. But unfortunately I can't get notifications with incoming mails.

Do you have an idea for the reason?

![html_notifier](https://f.cloud.github.com/assets/6803771/2282441/2872a014-9fae-11e3-846a-ededddb639e9.png)

**Comment by MagicFab** [comment]
I've reproduced this in the latest versions of Firefox and Chromium in Debian (37.0.1 and 41.0.2272.118 respectively).

**Comment by andreapernici** [comment]
I have the same problem. It doesn't work.

**Comment by juhanihaapala** [comment]
I have had this bug from the beging when I started using the plugin. Now looked at the code and found a solution for that see my pull request https://github.com/kitist/html5_notifier/pull/12
